import Navbar from './Navbar';
import Footer from './Footer';
import { ReactNode } from 'react';
import Head from 'next/head';
type LayoutProps = {
	children: ReactNode;
};

export default function Layout({ children }: LayoutProps) {
	return (
		<>
			<Head>
				<title>Dispatcher</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<meta name='author' content='John Rommel Octaviano' />
				<meta
					name='description'
					content='Interactive news allows you to stay up to date with the latest stories and events. With just a few clicks, you can access the latest news from around the world, as well as explore topics of interest to you. You can easily customize your news feed by selecting topics and sources that are of interest to you.'
				/>
				<meta name='designer' content='John Rommel Octaviano' />
				<meta name='reply-to' content='johnrommel.octaviano@gmail.com' />
				<meta name='owner' content='John Rommel P. Octaviano' />
				<meta name='summary' content='John Rommel Octaviano' />
				<meta name='directory' content='submission' />
				<meta name='coverage' content='Worldwide' />
				<meta name='distribution' content='Global' />
				<meta name='subject' content='news, interactive, information, free' />
				<meta name='keywords' content='news, interactive, information, free' />
				<meta name='topic' content='Password Generator' />
				<meta name='category' content='Security' />
				<meta name='target' content='all' />
				<meta name='audience' content='all' />
				<meta name='rating' content='General' />
				<meta
					name='generator'
					content='Visual Studio Code, XD, Photoshop, Firefox Developer Edition, Windows Terminal, etc.'
				/>
				<meta name='referrer' content='no-referrer' />
				<meta name='fragment' content='!' />
				<meta
					name='format-detection'
					content='telephone=no,date=no,address=no,email=no,url=no'
				/>
				<meta name='mssmarttagspreventparsing' content='true' />
				<meta name='HandheldFriendly' content='True' />
				<meta name='robots' content='index,follow' />
				<meta name='googlebot' content='index,follow' />
				<meta name='google' content='nositelinkssearchbox' />
				<meta name='slurp' content='noydir' />
				<meta http-equiv='Window-Target' content='_top' />
				<meta http-equiv='Pragma' content='no-cache' />
				<meta http-equive='expires' content='-1' />
				<meta
					http-equiv='Page-Enter'
					content='RevealTrans(Duration=1.0,Transition=1)'
				/>
				<meta
					http-equiv='Page-Exit'
					content='RevealTrans(Duration=1.0,Transition=1)'
				/>
				<meta name='msapplication-navbutton-color' content='#0072F5' />
				<meta http-equiv='imagetoolbar' content='no' />
				<meta name='ICBM' content='14.169648, 121.333653' />
				<meta name='geo.position' content='14.169648;121.333653' />
				<meta name='geo.region' content='PH-LAG' />
				<link
					rel='author'
					href='data:text/plain;base64,VGhpcyBwZXJzb25hbCBwb3J0Zm9saW8gaXMgYnVpbHQgYnkgSm9obiBSb21tZWwgT2N0YXZpYW5vLCBhIEZyb250IEVuZCBEZXZlbG9wZXIsIFVzZXIgSW50ZXJmYWNlIERlc2lnbmVyLCBHcmFwaGljIERlc2lnbmVyLCBhbmQgVGVjaG5pY2FsIEJsb2dnZXIgYmFzZWQgaW4gdGhlIFBoaWxpcHBpbmVzLg0KDQpGYWJyaWNhdGluZyB0aGluZ3MgaXMgYSB0aW1lbGVzcyBqb3VybmV5LiBBIG1hZ25pZmljZW50IHZveWFnZSB0aGF0IGxlYWRzIHRvIHRoZSBwYXRoIG9mIHBvc3NpYmlsaXRpZXMuIENvbnRpbnVpbmcgb24gdG8gdGhlIHByb2xvbmdlZCBlbmQu'
				/>
				<link rel='me' href='mailto:johnrommel.octaviano@gmail.com' />
				<link rel='me' href='sms:+639562057280' />
				<link
					rel='icon'
					sizes='192x192'
					href='https://img.icons8.com/3d-fluency/1500/null/news.png'
				/>
				<link
					rel='mask-icon'
					href='https://img.icons8.com/3d-fluency/1500/null/news.png'
					color=''
				/>
				<meta name='apple-mobile-web-app-capable' content='yes' />
				<meta
					name='apple-mobile-web-app-status-bar-style'
					content='black-translucent'
				/>
				<meta
					name='apple-mobile-web-app-title'
					content='John Rommel Octaviano'
				/>
				<meta name='apple-mobile-web-app-capable' content='yes' />
				<meta name='apple-mobile-web-app-status-bar-style' content='blue' />
				<meta property='og:type' content='website' />
				<meta property='og:title' content='Dispatcher' />
				<meta property='og:image' content='' />
				<meta property='og:image:alt' content='Dispatcher home page' />
				<meta property='og:image:type' content='image/png' />
				<meta property='og:image:width' content='2000' />
				<meta property='og:image:height' content='1778' />
				<meta
					property='og:description'
					content='Interactive news allows you to stay up to date with the latest stories and events. With just a few clicks, you can access the latest news from around the world, as well as explore topics of interest to you. You can easily customize your news feed by selecting topics and sources that are of interest to you.'
				/>
				<meta property='og:locale' content='en_PH' />
				<meta name='twitter:card' content='website' />
				<meta name='twitter:site' content='@ctvnjhnrmmlp' />
				<meta name='twitter:creator' content='@ctvnjhnrmmlp' />
				<meta name='twitter:creator:id' content='1330479663420850176' />
				<meta name='twitter:title' content='Dispatcher' />
				<meta
					name='twitter:description'
					content='Interactive news allows you to stay up to date with the latest stories and events. With just a few clicks, you can access the latest news from around the world, as well as explore topics of interest to you. You can easily customize your news feed by selecting topics and sources that are of interest to you.'
				/>
				<meta name='twitter:image' content='' />
				<meta name='twitter:image:alt' content='Dispatcher home page' />
			</Head>
			<Navbar />
			<main>{children}</main>
			<Footer />
		</>
	);
}
